# 反向代理配置
  
# 配置文件目录设置
config_dir: "conf.d"  # 配置文件目录，系统会扫描该目录下的所有.yaml配置文件
  
# 主配置文件 - 系统全局配置
# 具体的域名和服务配置在conf.d目录下的配置文件中

# 中间件配置
middlewares:  
  # 日志中间件 - 记录请求日志
  - name: "logging"
    enabled: true
    config:
      level: "info"

  # 限流中间件 - 请求频率限制
  - name: "rate_limit"
    enabled: true
    config:
      requests_per_minute: 100
      burst_size: 20
  
  # CORS中间件 - 跨域资源共享
  - name: "cors"
    enabled: true
    config:
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE"]
      allowed_headers: ["Content-Type", "Authorization"]
  
  # 缓存中间件 - 响应缓存
  - name: "cache"
    enabled: true
    config:
      cache_dir: "./cache/responses"
      default_ttl: 300  # 5分钟
      max_cache_size: 104857600  # 100MB
      cache_key_headers: ["Authorization", "Accept-Language"]
      cache_control: true
      vary_headers: ["Accept", "Accept-Language", "Authorization"]

# 高级配置
advanced:
  # 连接超时设置
  timeout:
    read_timeout: 30
    write_timeout: 30
    dial_timeout: 30
  port: 80
  security:
    deny_hidden_files: true