# 反向代理配置
server:
  # 端口配置现在在host_rules中定义
  
# 配置文件目录设置
config_dir: "conf.d"  # 配置文件目录，系统会扫描该目录下的所有.yaml配置文件
  
# 主配置文件 - 系统全局配置
# 具体的域名和服务配置在conf.d目录下的配置文件中

# 中间件配置
middlewares:  
  # 日志中间件 - 记录请求日志
  - name: "logging"
    enabled: true
    config:
      level: "info"

# 高级配置
advanced:
  # 连接超时设置
  timeout:
    read_timeout: 30
    write_timeout: 30
    dial_timeout: 30
  port: 80
  security:
    deny_hidden_files: true